# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brigitte Gong
email: brigittegong@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Psychology and Criminal Justice major at Northeastern University in Boston, MA who likes to dabble in photography and film.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brigittegong.com" # the base hostname & protocol for your site
instagram_username: brigittegong
github_username:  brigittegong

# Build settings
markdown: kramdown
